package user

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Repository struct {
	pool *pgxpool.Pool
}

func NewRepository(pool *pgxpool.Pool) *Repository {
	return &Repository{pool: pool}
}

func (r *Repository) CreateUser(ctx context.Context, user *User, profile *Profile) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	const userQuery = `
		INSERT INTO users (id, email, password_hash)
		VALUES ($1, $2, $3)
		RETURNING created_at, updated_at` // id is generated by DB or passed

	if user.ID == uuid.Nil {
		user.ID = uuid.New()
	}

	err = tx.QueryRow(ctx, userQuery, user.ID, user.Email, user.PasswordHash).Scan(&user.CreatedAt, &user.UpdatedAt)
	if err != nil {
		return fmt.Errorf("insert user: %w", err)
	}

	const profileQuery = `
		INSERT INTO profiles (id, user_id, first_name, last_name)
		VALUES ($1, $2, $3, $4)
		RETURNING created_at, updated_at` // id is generated by DB or passed

	if profile.ID == uuid.Nil {
		profile.ID = uuid.New()
	}
	profile.UserID = user.ID

	err = tx.QueryRow(ctx, profileQuery, profile.ID, profile.UserID, profile.FirstName, profile.LastName).Scan(&profile.CreatedAt, &profile.UpdatedAt)
	if err != nil {
		return fmt.Errorf("insert profile: %w", err)
	}

	return tx.Commit(ctx)
}

func (r *Repository) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	const query = `
		SELECT id, email, password_hash, created_at, updated_at
		FROM users
		WHERE email = $1` // email is unique

	var user User
	err := r.pool.QueryRow(ctx, query, email).Scan(
		&user.ID, &user.Email, &user.PasswordHash, &user.CreatedAt, &user.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("get user by email: %w", err)
	}

	return &user, nil
}

func (r *Repository) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (*Profile, error) {
	const query = `
		SELECT id, user_id, first_name, last_name, created_at, updated_at
		FROM profiles
		WHERE user_id = $1` // user_id is unique

	var profile Profile
	err := r.pool.QueryRow(ctx, query, userID).Scan(
		&profile.ID, &profile.UserID, &profile.FirstName, &profile.LastName, &profile.CreatedAt, &profile.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("get profile by user id: %w", err)
	}

	return &profile, nil
}
