// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/tailor": {
            "post": {
                "description": "Extracts text from a PDF resume, analyzes it against a vacancy text using LLM, and returns a tailored resume, cover letter, and match analysis.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tailor"
                ],
                "summary": "Tailor resume to vacancy",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Resume PDF file (max 10MB)",
                        "name": "resume",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Vacancy text (max 50KB)",
                        "name": "vacancy",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_puddingtonnn_getyouroffer_backend_internal_models.Result"
                        }
                    }
                }
            }
        },
        "/api/tools/extract-ocr": {
            "post": {
                "description": "Converts PDF to images and runs Tesseract OCR.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Extract text from PDF (OCR)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Resume PDF file",
                        "name": "resume",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.TextResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/tools/extract-text": {
            "post": {
                "description": "Attempts to extract text layer from PDF without OCR.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Extract text from PDF (Plain)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Resume PDF file",
                        "name": "resume",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.TextResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/users/login": {
            "post": {
                "description": "Authenticate user and return JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.authResponse"
                        }
                    }
                }
            }
        },
        "/api/users/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get profile of the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get current profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_puddingtonnn_getyouroffer_backend_internal_models.Profile"
                        }
                    }
                }
            }
        },
        "/api/users/register": {
            "post": {
                "description": "Create a new user and profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.authResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_puddingtonnn_getyouroffer_backend_internal_models.Gap": {
            "type": "object",
            "properties": {
                "requirement": {
                    "type": "string"
                },
                "suggestion": {
                    "type": "string"
                }
            }
        },
        "github_com_puddingtonnn_getyouroffer_backend_internal_models.Match": {
            "type": "object",
            "properties": {
                "evidence": {
                    "type": "string"
                },
                "requirement": {
                    "type": "string"
                }
            }
        },
        "github_com_puddingtonnn_getyouroffer_backend_internal_models.Profile": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_puddingtonnn_getyouroffer_backend_internal_models.Result": {
            "type": "object",
            "properties": {
                "cover_letter": {
                    "type": "string"
                },
                "gaps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_puddingtonnn_getyouroffer_backend_internal_models.Gap"
                    }
                },
                "keywords_to_add": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "match_score": {
                    "type": "number"
                },
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_puddingtonnn_getyouroffer_backend_internal_models.Match"
                    }
                },
                "tailored_resume": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http.ErrorResponse": {
            "description": "The shared error envelope for all API errors.",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error message in Russian",
                    "type": "string"
                }
            }
        },
        "internal_transport_http.TextResponse": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http.authResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http.loginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http.registerRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Type \"Bearer \u003cyour-jwt-token\u003e\" to authenticate.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GetYourOffer API",
	Description:      "API server for GetYourOffer service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
